import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { Inter } from "next/font/google";
import { Navbar01 } from "@/components/nav-bar";
import QueryProvider from "@/components/query-provider"; // ✅ import
import Footer from "@/components/footer-section";

// const dreamToBerich = localFont({
//   src: "../public/fonts/DreamToBerich.ttf",
// });

const inter = Inter({
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} antialiased`}
      >
        <QueryProvider>
          <Navbar01 />
          {children}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
